### ISSUE TITLE
关于J1939.c中的SetAddressFilter函数调用问题。

### ISSUE THREAD

**Issue by SummerFalls** [XeiTongXueFlyMe/J1939#14]
- 版本：`2.1.0 稳定发布版 on 20 Jan 2018`
- 问题描述：在移植过程中，手册以及代码注释有提到使用软件滤波器时，可跳过函数：`J1939_SetAddressFilter`的移植和CAN硬件滤波器的配置，而软件滤波实际上是由库内的`SetAddressFilter`函数实现的，通过IDE的搜索功能并未发现`SetAddressFilter`函数有在其它地方被调用的情况，并且本函数未在头文件中向外提供声明，所以想确认一下。

**Comment by xieming0608** [comment]
很抱歉，已经有3年没做汽车电子了！我也记不清了







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LINNY <notifications@github.com&gt;
发送时间: 2020年7月3日 18:28
收件人: XeiTongXueFlyMe/J1939 <J1939@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[XeiTongXueFlyMe/J1939] 关于J1939.c中的SetAddressFilter函数调用问题。 (#14)





  
版本：2.1.0 稳定发布版 on 20 Jan 2018 

问题描述：在移植过程中，手册以及代码注释有提到使用软件滤波器时，可跳过函数：J1939_SetAddressFilter的移植和CAN硬件滤波器的配置，而软件滤波实际上是由库内的SetAddressFilter函数实现的，通过IDE的搜索功能并未发现SetAddressFilter函数有在其它地方被调用的情况，并且本函数未在头文件中向外提供声明，所以想确认一下。
